<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<!DOCTYPE Produits [
  <!ELEMENT Produits (Produit*)>
  <!ELEMENT Produit (id, nom, description)>
  <!ELEMENT id ANY>
  <!ELEMENT nom (#PCDATA)>
  <!ELEMENT description (#PCDATA)>
]>

<Produits>
  <Produit>
    <id>0</id>
    <nom>Stylo</nom>
    <description>Indispensable pour écrire.</description>
  </Produit>
  <Produit>
    <id>1</id>
    <nom>Banane</nom>
    <description>Un fruit sphérique.</description>
  </Produit>
  <Produit>
    <id>2</id>
    <nom>Table</nom>
    <description>Un meuble.</description>
  </Produit>
  <Produit>
    <id>3</id>
    <nom>新唐人電視台</nom>
    <description>Test UTF-8.</description>
  </Produit>
  <Produit>
    <id>4</id>
    <nom>chaise</nom>
    <description>Un nouveau meuble.</description>
  </Produit>
</Produits>
